config/routes.rb
Rails.application.routes.draw do
  get 'login.html' => 'sessions#new', as: 'login'

  get 'signup.html' => 'users#new', as: 'signup'

  root 'home#index'

  resources :users, only: :create
  resources :sessions, only: :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/login_helper.rb
module LoginHelper
  extend ActiveSupport::Concern

  def login_with_cognito_identity
    cognitoidentity = Aws::CognitoIdentity::Client.new(region: ENV['AWS_REGION'])
    cognitoidentity.get_id(account_id: ENV['AWS_ACCOUNT_ID'],
                           identity_pool_id: ENV['COGNITO_IDENTITY_POOL_ID'],
                           logins: login_params)
  end

  def login_params
    case params[:login_type]
    when 'facebook'
      {'graph.facebook.com' => params[:fb_access_token]}
    when 'user_pools'
      {ENV['COGNITO_USER_POOL_LOGIN_KEY'] => params[:id_token]}
    else
      raise ArgumentError, 'Unsupported login type.'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include LoginHelper

  def new
  end

  def create
    result = login_with_cognito_identity
    # NOTE Do something to login.
    # session[:identity_id] = result.identity_id
    render :json => {identity_id: result.identity_id}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include LoginHelper

  def new
  end

  def create
    result = login_with_cognito_identity
    # NOTE Do something to register. Create user, send registration email, etc.
    render :json => {identity_id: result.identity_id}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
  <div class="jumbotron">
    <h1>Hello Cognito</h1>
    <p>This is a sample project of Cognito User Pools and Federated Identity.</p>
    <p id="top_buttons"><%= link_to 'Go to Login', login_path, class:"btn btn-primary btn-lg", role:"button" %> <%= link_to 'Go to Signup', signup_path, class:"btn btn-primary btn-lg", role:"button" %></p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CognitoSample</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="AppInfo" content="Our app info"
                         data-facebook-app-id="<%= ENV['FACEBOOK_APP_ID'] %>"
                         data-aws-region="<%= ENV['AWS_REGION'] %>"
                         data-cognito-identity-pool-id="<%= ENV['COGNITO_IDENTITY_POOL_ID'] %>"
                         data-cognito-user-pool-id="<%= ENV['COGNITO_USER_POOL_ID'] %>"
                         data-cognito-client-id="<%= ENV['COGNITO_CLIENT_ID'] %>">
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarExample">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Cognito Sample</a>
      </div>

      <div class="collapse navbar-collapse" id="navbarExample">
        <div id="login_and_signup_menus">
          <ul class="nav navbar-nav">
            <li id="menu_user_login"><%= link_to 'Login', login_path %></li>
            <li id="menu_user_signup"><%= link_to 'Signup', signup_path %></li>
          </ul>
        </div>
        <ul class="nav navbar-nav" id="logged_in_menus" style="display:none">
          <li><a id="user_logout_btn" href="#" data-confirm="Logout ?">Logout</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
<%= yield %>
  </div>

</body>
</html>

app/views/users/new.html.erb
<form class="form-signup">
  <div class="page-header">
    <h2 class="form-signup-heading">Signup</h2>
  </div>

  <div class="message alert" role="alert" style="display:none;"></div>

  <div class="form-group">
    <label for="email" class="sr-only">Email</label>
    <input type="text" id="email" class="form-control" placeholder="Enter Email" required autofocus></input>
  </div>
  <div class="form-group">
    <label for="password" class="sr-only">Password</label>
    <input type="password" id="password" class="form-control" placeholder="Enter Password" required></input>
  </div>
  <br/>
  <button type="submit" class="btn btn-lg btn-primary btn-bloc" id="user_add_btn">Signup</button>
</form>

<form class="form-activation" style="display:none">
  <div class="page-header">
    <h2 class="form-activation-heading">Activation</h2>
  </div>

  <div class="message alert" style="display:none;"></div>

  <div class="form-group">
    <label for="activationCode" class="sr-only">Activation Code</label>
    <input type="text" id="activationCode" class="form-control" placeholder="Enter Activation Code" required autofocus></input>
  </div>
  <input type="hidden" name="activationEmail" id="activationEmail">
  <br/>
  <button type="submit" class="btn btn-lg btn-primary btn-bloc" id="user_activation_btn">Activation</button>
</form>

<div class="success-box" style="display:none">
  <div class="page-header">
    <h2 class="success-box-heading">Welcome</h2>
  </div>
  <div class="message alert alert-success">Registration complete.</div>
</div>

<br>

<%= link_to("Login with Facebook", "javascript:void(0);", id: "fb-login-button", class: "btn btn-lg btn-primary") %>

<script>
function statusChangeCallback(response) {
  // The response object is returned with a status field that lets the
  // app know the current login status of the person.
  // Full docs on the response object can be found in the documentation
  // for FB.getLoginStatus().
  if (response.status === 'connected') {
    // Logged into your app and Facebook.
    $.post("/users",
      {
        'login_type': 'facebook',
        'fb_access_token': response.authResponse.accessToken,
      }, function(data) {
        loginStatusManager.login(data['identity_id']);
        var url = "/";
        $(location).attr("href", url);
      }, 'json'
    );
  } else if (response.status === 'not_authorized') {
    // The person is logged into Facebook, but not your app.
  } else {
    // The person is not logged into Facebook, so we're not sure if
    // they are logged into this app or not.
  }
}

window.fbAsyncInit = function() {
  var appId = $('meta[name=AppInfo]').data('facebook-app-id');
  FB.init({
    appId      : appId,
    xfbml      : true,
    version    : 'v2.7'
  });

  document.getElementById('fb-login-button').addEventListener('click', function() {
    //do the login
    FB.login(function(response) {
        if (response.authResponse) {
          //user just authorized your app
          statusChangeCallback(response);
        }
    }, {scope: 'public_profile', return_scopes: true});
  }, false);
};

(function(d, s, id){
   var js, fjs = d.getElementsByTagName(s)[0];
   if (d.getElementById(id)) {return;}
   js = d.createElement(s); js.id = id;
   js.src = "//connect.facebook.net/ja_JP/sdk.js";
   fjs.parentNode.insertBefore(js, fjs);
 }(document, 'script', 'facebook-jssdk'));
</script>